### ISSUE TITLE
youtube-dl-GUI portable

### ISSUE THREAD

**Issue by candrapersada** [yasoob/youtube-dl-GUI#10]
how to use youtube-dl-GUI portable for Windows?
and why Dropbox not working?

**Comment by oleksis** [comment]
> how to use youtube-dl-GUI portable for Windows?

I think add one exe to the release using PyInstaller with all the dependency like Qt

> and why Dropbox not working?

What problem specifically you have with Dropbox. We update youtube-dl to the latest version available. You can share some logs of your problem?

**Comment by candrapersada** [comment]
> What problem specifically you have with Dropbox. We update youtube-dl to the latest version available. You can share some logs of your problem?

https://www.dropbox.com/s/oj8dh4q82tofk34/youtube-dl.exe
![1](https://user-images.githubusercontent.com/36833664/100492681-36729600-3161-11eb-98f8-3eb28303924d.PNG)

![2](https://user-images.githubusercontent.com/36833664/100492643-c3691f80-3160-11eb-97a7-ab5ce97c8a12.PNG)

**Comment by oleksis** [comment]
> ![1](https://user-images.githubusercontent.com/36833664/100492681-36729600-3161-11eb-98f8-3eb28303924d.PNG)

Check this [Windows](https://github.com/yasoob/youtube-dl-GUI#windows) seccion and try. We will add the executable file to the releases

**Comment by oleksis** [comment]
> how to use youtube-dl-GUI portable for Windows?

Now you can download a .exe for Windows in the Releases: https://github.com/yasoob/youtube-dl-GUI/releases/download/v0.4.0/youtube-dl-gui.exe
